[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true
allowed-paths = ["deployments"]
chain_id = 84532

remappings = ["@openzeppelin=lib/openzeppelin-contracts"]
# The remappings are used to map the imports in your Solidity files to the correct paths.

[profile.out]
out = "out"
libs = ["lib"]
# The out section specifies the output directory for the compiled contracts and libraries.
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
